########################################################################################
#   __________  ______           ______  ________  ___   ______   ___         __  __   #
#  /_  __/ __ \/ ____/________ _/ __/ /_/  _/ __ \/   | / ____/  /   | __  __/ /_/ /_  #
#   / / / /_/ / /   / ___/ __ `/ /_/ __// // / / / /| |/ /      / /| |/ / / / __/ __ \ #
#  / / / ____/ /___/ /  / /_/ / __/ /__/ // /_/ / ___ / /___   / ___ / /_/ / /_/ / / / #
# /_/ /_/    \____/_/   \__,_/_/  \__/___/_____/_/  |_\____/  /_/  |_\__,_/\__/_/ /_/  #
#                                                                                      #
########################################################################################

###################
#     注意事项     #
###################

# 创建 OAuth2 应用 https://auth.tpcraft.net/oauth2/client
# 如果域名未备案请使用IP作为回调地址

###################
#     配置文件     #
###################

# Web服务器端口
webPort: 5900

# OAuth2
oauth2:
  clientId: '' # 标识
  clientSecret: '' # 密钥
  redirectUri: '' # 回调地址

# 登入消息
# 变量 %player%(玩家名称)
loginMessage:
  enable: true # 是否启用
  join: '[&2+&r] &e%player%' # 进入消息
  leave: '[&4-&r] &e%player%' # 离开消息

# 自动登入
autoLogin:
  enable: false # 是否启用
  expires: 3600 # 超时时长(秒)

# 固定登入坐标
loginPosition:
  enable: false # 是否启用
  x: 0.0 # X轴
  y: 0.0 # Y轴
  z: 0.0 # Z轴

# 白名单
# 吐槽 原版白名单一点都不好用！
whiteList:
  enable: false # 是否启用
  allowPlayers: [ ] # 白名单列表